### ISSUE TITLE
Balancing ideas

### ISSUE THREAD

**Issue by Zentheon** [JayCeeCreates/earlygame#6]
This mod is starting to show a lot of promise, so I went ahead and checked it out. I'm pretty impressed by it, and has ideas in it that I felt other mods lack in, so props to that.

However, there are some aspects which feel out of place or could use improvement. In my testing of it, these are some of the points that I came across:

1. First of all, the mining speed for dirt feels a bit too slow. I like that you're not able to plow through it anymore, but it gets annoying before long without having a shovel.

2. To further on the first point, it would be neat if dirt could actually drop flint only while mining by hand. This could be at a rate lower to that of gravel, but only by a bit.

3. The next thing is that the flint saw seems kind of useless. It isn't able to chop logs into planks like the others are, and as far as I could tell, only had the ability to strip planks. Even if it worked in the exact same way as the rest, I doubt it would serve much purpose.

4. The rate for fiber dropping from grass feels kind of low. It seems like the average is around one lashing per knife, which doesn't last long when the bare minimum for getting to copper is an axe and pick. To that end, one possible idea to make it a bit more dynamic would be to have fiber drop with a low chance from grass with just bare hands, which a flint knife would need one of to be able to craft it. Once you have a knife, the rate would be significantly higher (Maybe around 50% or more) so it becomes much easier to get more fiber for the lashings. 

5. This one is kind of just a randomly coined idea but it would make sense in the mod nonetheless, and that is adding a woodcutter into it, similar to the stonecutter. This could have the purpose of allowing for items like planks to be crafted in a GUI instead of by interacting with a block, but at the cost of needing an iron ingot to make the cutter. This would probably render late-game saws to be useless, but maybe there are other uses that they could have? But even if not, it would still be hard to tote around yet another tool in an already crowded inventory.

**Comment by JayCeeCreates** [comment]
Yo, thanks for your input!

These are some interesting ideas I would happily look into. Balance is an important part of this mod, so ideas like this would help me create a better balance for every player out there. Anyway, here's what I could say about them.

1. I take you are using dirt for some platforming purposes? I may be wrong tho. Other than that, I'll look into it and see the right amount of slowness. For now, you could disable the **Make Ground Blocks Harder** option to revert to the normal digging speed.
2. I'll see how it would work out. Dirt is a common sighting, and even if I add the break speed factor, I might adjust the rate to be lower than I think you might expect.
3. Have you tried sneaking then interacting with the wood using the flint saw? If so, my bad. But tbh, I kinda feel the same way, just for a lil bit. The tool won't be removed for the time being, but I'll see what other user inputs have to say.
4. Someone actually pointed that out to me that one day, and I'm currently looking for it.
5. I dunno what to say about this tbh other than that you could use **Charm** if you want a woodcutter. Like you said, it would render the late-game saws useless. That's why saws have the purpose to convert wood into planks and planks into sticks, giving you the maximum amount.

Again, these ideas are interesting and I might implement some of them in the next update. If you have further inquiries, let me know.

Stay safe on the way out!

**Comment by Zentheon** [comment]
Hey, glad to see the feedback to this! And yeah, your points about all those makes sense. 

The main thing I meant about the flint saw is that it doesn't allow for cutting logs into planks like all the other ones. I made a typo in "stripping planks" but what I meant to say was that the only thing I noticed it could do was "strip logs." Other than that, I like the usefulness of those tools, but without a way to gather mass quantities of planks other than sawing each individual log was why I made the woodcutter suggestion. Charm would definitely fit in with this mod pretty well, so I suppose that's a good alternative for those who like building huge houses or otherwise using a lot of wood.

Also with the dirt blocks, yes, the main purpose was gathering some for platforming and whatnot. It isn't a big deal to have to gather some up by hand, but the flint dropping from it thing was the other main reason why I gave that suggestion. Alternatively, flint could instead have a chance at spawning naturally on the surface like sticks and stones, but at a low rate. 

But yea, 'bout all I got as far as suggestions go. Like this mod quite a bit, as it's nice to finally have a good progression overhaul mod come to fabric.

**Comment by JayCeeCreates** [comment]
Hi! Just to let you know the mod has been updated to implement some balancing stuff you suggested. The flint saw not performing properly was just a mere mistake of forgetting to put it in the item tags database lmao

You can download it on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/earlygame/files/3200431) or through the [Releases](https://github.com/JayCeeCreates/earlygame/releases/tag/1.16.x-1.1.0b) page.

Lemme know if you have further inquiries.
