### ISSUE TITLE
Wood, Stone, and Non-vanilla axes don't chop logs to planks, etc. properly

### ISSUE THREAD

**Issue by Beethoven-n** [JayCeeCreates/earlygame#9]
After enabling wood and stone tools (the flint tools are far _too_ useless to go mining for it,) I found that chopping logs into planks with them simply breaks the block, not giving any drops.

**Comment by JayCeeCreates** [comment]
Yo, thanks for your input!

Pro tip: With a flint pickaxe, prioritize mining 5 copper ores and making a furnace to give you a copper pickaxe and sword after smelting. I made it so that flint tools would easily break because I know some players would most likely make a wooden pickaxe only, mine cobbles to make some stone tools, and then yeet the wooden pick. Of course, it's all up to the player's playstyle preference, hence the configuration (why do I have to explain this h).

Now about the issue, I kinda didn't notice that (because I mostly play my mod without those tools lmao) so sorry for not finding it out sooner. I'll be looking into it~

**Comment by Beethoven-n** [comment]
of course! also, i noticed breaking dirt has a very small chance of making flint, so maybe make a flint shovel so people can use that chance when they need flint most?

**Comment by Beethoven-n** [comment]
found out that modded axes do this too, like the Tech Reborn ruby axe

**Comment by JayCeeCreates** [comment]
Latest release is out! It should be fixed by now.
